import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig, type Plugin, type ResolvedConfig } from 'vite';
import svg from '@poppanator/sveltekit-svg';

let HEADERS = `
/*
  Accept-CH: Width, Viewport-Width, Sec-CH-Width, Sec-CH-Viewport-Width, Sec-CH-Viewport-Height, Sec-CH-UA-Mobile
`.trim();
let ROUTE_PATH = '/src/routes';
let ALWAYS_PRELOADED_BUNDLED = [
  {
    file: 'src/lib/fonts/DMSans.text.woff2',
    as: 'font'
  }
];
let ALWAYS_PRELOADED_STATIC = [
  {
    path: '/api/background.svg',
    as: 'image'
  }
];

let config: ResolvedConfig;
const plugin: Plugin = {
  name: 'generate-headers',

  configResolved(resolvedConfig) {
    console.log(resolvedConfig);
    config = resolvedConfig;
  },

  async generateBundle(options, bundle, isWrite) {
    let baseFsPath = config.root + ROUTE_PATH;
    console.log(`Using base path ${baseFsPath}`);

    let fileToAssetMap: Record<string, Set<string>> = {};
    let pathToCssMap: Record<string, Set<string>> = {};

    for (const chunk of Object.values(bundle)) {
      if (chunk.type === 'asset') {
        for (const name of chunk.originalFileNames) {
          fileToAssetMap[name] = new Set<string>([...(fileToAssetMap[name] || []), chunk.fileName]);
        }
      }

      if (chunk.type !== 'chunk' || !chunk.isDynamicEntry || !chunk.isEntry) {
        continue;
      }

      // Get CSS files
      let cssFiles = new Set<string>();
      chunk.viteMetadata?.importedCss?.forEach((file) => cssFiles.add(file));

      for (const imported of chunk.imports) {
        let importedChunk = bundle[imported];

        if (importedChunk.type !== 'chunk') {
          continue;
        }

        importedChunk.viteMetadata?.importedCss?.forEach((file) => cssFiles.add(file));
      }

      // Get path
      let path = null;
      for (const alias of chunk.moduleIds) {
        if (!alias.startsWith(baseFsPath)) {
          continue;
        }

        if (!alias.endsWith('/+page.svelte')) {
          continue;
        }

        path = alias.replace(baseFsPath, '').replace('+page.svelte', '');
        if (path !== '/') {
          // Remove trailing slash like SvelteKit does
          path = path.replace(/\/$/, '');
        }
      }

      if (path === null) {
        this.warn(`Failed to determine path for chunk ${chunk.fileName} (moduleIds: ${chunk.moduleIds})`);
        continue;
      }

      pathToCssMap[path] = cssFiles;
    }

    let alwaysIncluded = [...ALWAYS_PRELOADED_STATIC];

    for (const toResolve of ALWAYS_PRELOADED_BUNDLED) {
      const resolved = fileToAssetMap[toResolve.file];
      if (resolved === undefined) {
        console.log(fileToAssetMap);
        return this.error(`Failed to resolve file ${toResolve.file}`);
      }

      for (const file of resolved.keys()) {
        alwaysIncluded.push({
          path: file,
          as: toResolve.as
        });
      }
    }

    let headerOutput = `${HEADERS}\n\n# generated by generate-headers plugin`;

    for (const [path, files] of Object.entries(pathToCssMap)) {
      headerOutput += `\n${path}\n  Link: `;
      const headers = [...alwaysIncluded];

      for (const file of files) {
        headers.push({
          path: file,
          as: 'style'
        });
      }

      headerOutput += headers
        .map((v) => {
          let header = `<${v.path}>; rel="preload"; as="${v.as}"; nopush`;
          if (v.as === 'font') {
            header += '; crossorigin="anonymous"';
          }
          return header;
        })
        .join(',');
      headerOutput += '\n';
    }

    console.log(headerOutput);

    this.emitFile({
      type: 'asset',
      fileName: '_headers',
      source: headerOutput
    });
  }
};

export default defineConfig({
  plugins: [
    sveltekit(),
    svg({
      svgoOptions: {
        plugins: [
          {
            name: 'preset-default',
            params: {
              overrides: {
                removeViewBox: false // Why is this on by default!?
              }
            }
          }
        ]
      }
    }),
    plugin
  ],
  build: {
    cssMinify: 'lightningcss',
    modulePreload: false
  }
});
